In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6])

In [3]:
a[3], a[-2]

(4, 5)

In [4]:
a[2:-1]

array([3, 4, 5])

In [5]:
a.dot(a)

91

In [6]:
a.reshape((3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [7]:
a.reshape((a.size,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [8]:
v = a[:,np.newaxis]
v

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [9]:
v.T.dot(v)

array([[91]])

In [10]:
v.dot(v)

ValueError: shapes (6,1) and (6,1) not aligned: 1 (dim 1) != 6 (dim 0)

In [11]:
v.dot(v.T)

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [12]:
np.einsum('i, j -> ij', a, a)

array([[ 1,  2,  3,  4,  5,  6],
       [ 2,  4,  6,  8, 10, 12],
       [ 3,  6,  9, 12, 15, 18],
       [ 4,  8, 12, 16, 20, 24],
       [ 5, 10, 15, 20, 25, 30],
       [ 6, 12, 18, 24, 30, 36]])

In [13]:
np.einsum('i, i', a, a)

91

In [14]:
M = np.random.randn(6,6)
M.dot(v)

array([[ -1.37576135],
       [ -1.9739452 ],
       [ -5.93289831],
       [ -3.29319616],
       [  2.81342481],
       [-15.47687558]])

In [15]:
np.einsum('ij, jk -> ik', M, v)

array([[ -1.37576135],
       [ -1.9739452 ],
       [ -5.93289831],
       [ -3.29319616],
       [  2.81342481],
       [-15.47687558]])

In [16]:
np.einsum('ij, j -> i', M, a)

array([ -1.37576135,  -1.9739452 ,  -5.93289831,  -3.29319616,
         2.81342481, -15.47687558])

In [17]:
a>2

array([False, False,  True,  True,  True,  True])

In [18]:
cond = np.logical_and(a>2, a<5)

In [19]:
cond

array([False, False,  True,  True, False, False])

In [20]:
cond.astype(np.int)

array([0, 0, 1, 1, 0, 0])

In [21]:
cond.sum()

2

In [22]:
a[cond]

array([3, 4])

In [23]:
a.shape, cond.shape

((6,), (6,))

In [24]:
a[a>2]

array([3, 4, 5, 6])

In [25]:
b = a[:-1] # not a copy anymore, use a.copy()

In [26]:
b[0] = 99

In [27]:
b

array([99,  2,  3,  4,  5])

In [28]:
a

array([99,  2,  3,  4,  5,  6])